### ISSUE TITLE
Herokuapp seems dead :D

### ISSUE THREAD

**Issue by Flydiverny** [osowskit/jenkins-deprecation-app#1]
Was planning to give this a try today, but seems like the herokuapp is dead https://service-replacement-app.herokuapp.com/ any plan to fix it?

**Comment by osowskit** [comment]
@Flydiverny sorry for missing this issue. You're best bet is contacting GitHub to help identify services installed on your account - https://developer.github.com/v3/guides/replacing-github-services/#all-other-users.

**Comment by Flydiverny** [comment]
@osowskit No worries, already solved it without this! :)
